### ISSUE TITLE
[SCS_Multiapi-Plugin] [AsyncApi] Fix how to get references from messages

### ISSUE THREAD

**Issue by dianaGomezGar** [sngular/scs-multiapi-plugin#146]
As a developer, I saw that In Asyncapi, when it receives a reference from a message without a payload field, this failed to generate the source code. I would like that this behaviour should be fixed, allowing to insert the message with direct reference.  

This is my failing event-api.yml file:

channels:
  userCreated:
    publish:
      operationId: "publishUser"
      message:
        $ref: '#/components/messages/UserCreated'
  createUser:
    subscribe:
      operationId: "subscribeUser"
      message:
        $ref: '#/components/messages/CreateUser'
components:
  messages:
    UserCreated:
      payload:
        $ref: '#/components/schemas/UserCreated'
    CreateUser:
      payload:
        $ref: '#/components/schemas/CreateUser'
        
        
 This is the error that it throws: 

Exception in thread "main" java.lang.StackOverflowError
        at com.fasterxml.jackson.databind.node.ObjectNode.findValues(ObjectNode.java:334)
        at com.fasterxml.jackson.databind.node.ObjectNode.findValues(ObjectNode.java:341)
        at com.fasterxml.jackson.databind.JsonNode.findValues(JsonNode.java:1048)
        at net.coru.api.generator.plugin.asyncapi.AsyncApiGenerator.checkReference(AsyncApiGenerator.java:236)
        at net.coru.api.generator.plugin.asyncapi.AsyncApiGenerator.processReference(AsyncApiGenerator.java:224)
        at net.coru.api.generator.plugin.asyncapi.AsyncApiGenerator.lambda$checkReference$6(AsyncApiGenerator.java:238)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at net.coru.api.generator.plugin.asyncapi.AsyncApiGenerator.checkReference(AsyncApiGenerator.java:238)
        at net.coru.api.generator.plugin.asyncapi.AsyncApiGenerator.processReference(AsyncApiGenerator.java:224)
        at net.coru.api.generator.plugin.asyncapi.AsyncApiGenerator.lambda$checkReference$6(AsyncApiGenerator.java:238)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at net.coru.api.generator.plugin.asyncapi.AsyncApiGenerator.checkReference(AsyncApiGenerator.java:238)
        at net.coru.api.generator.plugin.asyncapi.AsyncApiGenerator.processReference(AsyncApiGenerator.java:224)
        at net.coru.api.generator.plugin.asyncapi.AsyncApiGenerator.lambda$checkReference$6(AsyncApiGenerator.java:238)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
...

**Comment by AdrianLagarteraSngular** [comment]
This issue was resolved in this #175 so I close this one
