### ISSUE TITLE
infinite loop while generating source

### ISSUE THREAD

**Issue by eriknijs** [sngular/scs-multiapi-plugin#175]
When using nested schema definitions with `$ref` elements, the plugin goes into an infinite loop.

Here is a snippet of the asyncapi spec
```
... info / server / channels stuff omitted for readability
components:
    messages:
        mailRequest:
            title: A request to send a mail message
            summary: An event where a part of the application want a preformatted mail to be sent to a recipient
            contentType: application/json
            payload:
                $ref: '#/components/schemas/mailRequest'
    schemas:
        mailRequest:
            type: object
            additionalProperties: false
            properties:
                sender:
                    type: string
                    format: email
                    description: The sender mail address

                ... more properties here ...

                config:
                    $ref: '#/components/schemas/config'
        config:
            type: object
            properties:
                name: 
                    type: string
                ... more properties here ...
```

This produces the following output for the maven build

```
	at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.checkReference(AsyncApiGenerator.java:238)
	at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.processReference(AsyncApiGenerator.java:224)
	at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.lambda$checkReference$6(AsyncApiGenerator.java:238)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.checkReference(AsyncApiGenerator.java:238)
	at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.processReference(AsyncApiGenerator.java:224)
	at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.lambda$checkReference$6(AsyncApiGenerator.java:238)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.checkReference(AsyncApiGenerator.java:238)
	at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.processReference(AsyncApiGenerator.java:224)
	at com.sngular.api.generator.plugin.asyncapi.AsyncApiGenerator.lambda$checkReference$6(AsyncApiGenerator.java:238)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	... repeated ....
```

This error is resolved when the schema defs are nested without the refs

```
components:
    messages:
        mailRequest:
            title: A request to send a mail message
            summary: An event where a part of the application want a preformatted mail to be sent to a recipient
            contentType: application/json
            payload:
                type: object
                additionalProperties: false
                properties:
                    sender:
                        type: string
                        format: email
                        description: The sender mail address

	                ... more properties here ...

                    config:
                        description: Defines the additional properties which are available for the given template in the form of a key - value pair
                        type: object
                        properties:
                            ... more properties here ...
```

**Comment by eriknijs** [comment]
For reference, here is the full `asyncapi.yaml` file

```
asyncapi: 2.5.0
id: uri:myproject
info:
    title: myTitle
    version: 1.0.0
tags: []
servers:
    default:
        url: localhost
        protocol: jms
channels:
    outgoing:
        publish:
            operationId: onMailRequest
            message:
                $ref: '#/components/messages/mailRequest'
    incoming:
        subscribe:
            operationId: requestMail
            message:
                $ref: '#/components/messages/mailRequest'

components:
    messages:
        mailRequest:
            contentType: application/json
            payload:
                $ref: '#/components/schemas/mailRequest'
    schemas:
        mailRequest:
            type: object
            additionalProperties: false
            properties:
                sender:
                    type: string
                    format: email
                    description: The sender mail address
                recipients:
                    description: Email addresses of the recipients
                    type: array
                    items:
                        type: string
                        format: email
                config:
                    $ref: '#/components/schemas/config'
        config:
            description: Defines the additional properties which are available for the given template in the form of a key - value pair
            type: object
            properties:
                name: 
                    type: string
    
```

and the relevant part of the `pom.xml`
```
<plugin>
                <groupId>com.sngular</groupId>
                <artifactId>scs-multiapi-maven-plugin</artifactId>
                <version>4.3.13</version>
                <executions>
                    <execution>
                        <id>generateSupplier</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>asyncapi-generation</goal>
                        </goals>
                        <configuration>
                            <generatedSourcesFolder>generated-test-sources</generatedSourcesFolder>
                            <overwriteModel>true</overwriteModel>
                            <specFiles>
                                <specFile>
                                    <filePath>${project.basedir}/src/main/resources/asyncapi.yaml</filePath>
                                    <consumer>
                                        <ids>onMailRequest</ids>
                                        <apiPackage>gamesis.mail.messaging</apiPackage>
                                        <modelPackage>gamesis.mail.model</modelPackage>
                                    </consumer>
                                </specFile>
                            </specFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by mseijasm** [comment]
Hi @eriknijs 

Thank you for your collaboration. We are looking at it and we will get back to you as soon as possible.

**Comment by josemenvegsngular** [comment]
We have already merge a fix for this issue.
There was an issue when in the reference an `schema` and a `message` has the same name.

To validate it, we have included a [test](https://github.com/sngular/scs-multiapi-plugin/tree/main/multiapi-engine/src/test/resources/asyncapigenerator/testIssueInfiniteLoop) very similar to the example that you provided.

To avoid those problems, the code distinguish when the reference is a `schema` or a `message`, and depending on its type, the class is included in a different package.
Now, instead of including all the class described in the reference file in the same folder/package, it creates two folder/packages (`schemas` and `packages`) to avoid conflicts when a message and a schema has te same name.

And in the implementation, to avoid conflicts even when a message and a schema (both of them with the same name) are referenced in the same class, instead of importing the class, they are referenced by its full path.

Please, check if this solucion suits to your issue.

**Comment by eriknijs** [comment]
Hi,

Yes, thanks. This solves the issue
